CREATE TABLE IF NOT EXISTS recipe (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			name TEXT NOT NULL UNIQUE,
			time_to_cook BIGINT NOT NULL,
			source TEXT NOT NULL,
			video_link TEXT NOT NULL,
			directions TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);

CREATE TABLE IF NOT EXISTS product (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			name TEXT NOT NULL,
			amount INTEGER NOT NULL,
			amount_type TEXT NOT NULL,
			productrecipe INTEGER REFERENCES recipe(id) ON DELETE CASCADE
		);

CREATE TABLE IF NOT EXISTS label (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			name TEXT NOT NULL,
			labelrecipe INTEGER REFERENCES recipe(id) ON DELETE CASCADE
		);